# Database
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/mentalHealthTherapyCenter?createDatabaseIfNotExist=true
hibernate.connection.username=root
hibernate.connection.password=mysql

# Dialect
hibernate.dialect=org.hibernate.dialect.MySQLDialect

# DDL
hibernate.hbm2ddl.auto=update

# Show SQL
#hibernate.show_sql=true
#hibernate.format_sql=true

# Second-Level Cache
hibernate.cache.use_second_level_cache=true
hibernate.cache.use_query_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
hibernate.javax.cache.uri=mentalhealththerapycentersystem/ehcache.xml